spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/link_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
  error:
    include-message: always